objective:
  metrics:
    - metric: "RootMeanSquaredError"
      name: rmse_mangrove_lwp
      weight: 0.7
      properties:
        obs_file: "C:/Users/maria/Box/GradSchool/GitHub/fetch3_nhl/data/gh_data/gh_met_data_2023.csv"
        obs_var: 'WP'
        species: mangrove
        output_fname: 'ds_canopy.nc'
        output_var: 'H'
        fetch_data_func: get_model_obs
        #hour_range: [9, 21]
    - metric: "RootMeanSquaredError"
      name: rmse_mangrove_A
      weight: 0.3
      properties:
        obs_file: "C:/Users/maria/Box/GradSchool/GitHub/fetch3_nhl/data/gh_data/gh_met_data_2023.csv"
        output_fname: "A_gs_wplimit_timesteps.csv"
        obs_var: 'A'
        output_var: 'A'
        fetch_data_func: get_model_photo
  minimize: True

scheduler:
  n_trials: 2
  #tolerated_trial_failure_rate: 0.5
  #ttl_seconds_for_trials: 6000
  #run_trials_in_batches: true
  #max_pending_trials: 10
#generation_strategy:
  #num_initialization_trials: 5 #20
  #max_parallelism_override: 5 #10
#  parameter_keys: # defined dynamically in config to remap species_parameters keys to parameters

script_options:
  exp_name: gh_mangrove_test
  output_dir: C:/Users/maria/Box/GradSchool/GitHub/fetch3_nhl/output
  run_model: python -m fetch3 --config_path {config_path} --data_path {data_path} --output_path {trial_dir}
  # run_cmd: sbatch slurm_main.sh {config_path} {data_path} {trial_dir}
  wrapper_path: C:/Users/maria/Box/GradSchool/GitHub/fetch3_nhl/fetch3/optimize/fetch_wrapper.py
  wrapper_name: Fetch3Wrapper
  rel_to_launch: true

model_options:
  model_dir: .
  data_path: "C:/Users/maria/Box/GradSchool/GitHub/fetch3_nhl/data/gh_data"
  # File for input met data
  input_fname: "gh_met_data_2023.csv"
  met_column_labels:
    CO2_F_MDS: CO2_F

  # Start and end for the model
  start_time: "2023-01-02 12:00:00" #begining of simulation #6/9 is DOY 160
  end_time: "2023-01-02 14:00:00" #end #DOY190 - 7/10 is doy 191


  dt:  1800  #seconds - input data resolution
  tmin:  0  #tmin [s]

  # Site information
  latitude: 30.2876 #NHB buiding UT austin
  longitude: -97.7387 
  time_offset: -5 #Offset from UTC time, e.g CST = UTC -5 hrs for austin, TX

  # Run options

  # Printing slows down model run
  # Options to turn printing off or specify print frequency
  print_run_progress:  True  # Turn on/off printing for progress of time steps calculated
  print_freq:  2000  # Interval of timesteps to print if print_run_progress = True (e.g. 1 will print every time step)

  # Transpiration options: NHL or PM transpiration scheme
  transpiration_scheme:  1 # 0: PM transpiration; 1: NHL transpiration
  enable_osmoregulation: True

  # Numerical solution time and space constants
  #The finite difference discretization constants
  dt0:  20  #model temporal resolution [s]
  dz:  0.1  #model spatial resolution [m]
  stop_tol:  .0001  #0.0001  #stop tolerance of equation converging

  # Soil boundary conditions

  # Upper Boundary condition
  # 1 = no flux (Neuman)
  # 0 = infiltration

  # Bottom Boundary condition
  # 2 = free drainage
  # 1 = no flux (Neuman)
  # 0 = constant potential (Dirichlet)

  UpperBC: 0
  BottomBC: 0



  # Tree information
  # species:  "Oak"
  LAD_norm: 'LAD_data_AGPa.csv' #LAD data

  # Leaf area density formulation
  lad_scheme :  1  #0: default scheme, based on Lalic et al 2014; 1: scheme from NHL module

site_parameters:
  Soil_depth:
    type: fixed
    value: 6.0  # [m] depth of soil column
  sand_d:
    type: fixed
    value: 6.0 #4.2----top soil #m
  clay_d:
    type: fixed
    value: 1.0 #0------4.2 #m

  # Soil initial conditions
  initial_swc_clay:
    type: fixed
    value: 0.28 #from Verma et al

  #Infiltration
  frac_infiltration:
    type: fixed
    value: 0.5 #from Verma et al

  initial_swc_sand:
    type: fixed
    value: 0.08  # [m3 m-3] from Verma et al

  # soil bottom boundary condition
  soil_moisture_bottom_boundary:
    type: fixed
    value: 0.28  # [m3/m3]

  #SOIL PARAMETERS - USING VAN GENUCHTEN RELATIONSHIPS

  #CLAY
  alpha_1:
    type: fixed
    value: 0.8                       #soil hydraulic parameter [1/m]
  theta_S1:
    type: fixed
    value: 0.55                     #saturated volumetric soil moisture content [-]
  theta_R1:
    type: fixed
    value: 0.068                    #residual volumetric soil moisture content [-]
  n_1:
    type: fixed
    value: 1.5                           #soil hydraulic parameter  [-]
  Ksat_1:
    type: fixed
    value: 1.94e-7               #saturated hydraulic conductivity  [m/s]

  #SAND
  alpha_2:
    type: fixed
    value: 14.5
  theta_S2:
    type: fixed
    value: 0.47
  theta_R2:
    type: fixed
    value: 0.045
  n_2:
    type: fixed
    value: 2.4
  Ksat_2:
    type: fixed
    value: 3.45e-5

  #For NHL
  sum_LAI_plot:  # [m2leaf m-2ground]
    type: fixed
    value: 3  # Value from 2011 optical LAI measurements

  Cd:
    type: fixed
    value: 0.1 # Drag coefficient
  alpha_ml:
    type: fixed
    value: 0.1  # Mixing length constant

species_parameters:
  mangrove:
  # Soil and roots
    Root_depth:
      type: fixed
      value: 0.6  # [m] depth of root column

    #Soil stress parameters
    theta_1_clay:
      type: fixed
      value: 0.08
    theta_2_clay:
      type: fixed
      value: 0.12

    theta_1_sand:
      type: fixed
      value: 0.05
    theta_2_sand:
      type: fixed
      value: 0.09

    #ROOT PARAMETERS
    Kr:
      type: fixed
      value: 7.2e-10 #soil-to-root radial conductance [m/sPa]
    qz:
      type: fixed
      value: 9  #unitless - parameter for the root mass distribution - Verma et al., 2014
    Ksax:
      type: fixed
      value: 5.0e-8
      #bounds: [0.5e-9,2.0e-5]   #specific axial conductivity of roots  [ m/s]
    Aind_r:
      type: fixed
      value: 1          #m2 root xylem/m2 ground]

    #XYLEM PARAMETERS
    kmax:
      type: range
      value: 5.0e-8 #conductivity of xylem  [ m2/sPa]
      bounds: [0.5e-12, 2.0e-5]  #arbitrary range
 #arbitrary range

    ap:
      type: fixed
      value: 8.769734320082109e-07                                   #xylem cavitation parameter [Pa-1]
    bp:
      type: range
      value: -8158890.749381061                                #xylem cavitation parameter [Pa]                         #m2 xylem/m2 ground]
      bounds: [-10.0e+6, -4.0e+6]  #arbitrary range
    Phi_0:
      type: fixed
      value: 5.74e+8
      #bounds: [5.74e+5,5.74e+6]                             #From bohrer et al 2005
    p:
      type: range
      value: 20 
      bounds: [1,20]                                         #From bohrer et al 2005
    sat_xylem:
      type: range
      value: 0.573  # From bohrer et al 2005
      bounds: [0.4, 0.8]

    #TREE PARAMETERS
    taper_top:
      type: fixed
      value: 1.0  # Taper of xylem from base to crown
    sapwood_depth:  # Sapwood depth, measured at breast height [cm]
      type: fixed
      value: 0.50   # Updated with value for O6
    dbh:  # Diameter of plant at breast height [cm]
      type: fixed
      value: 0.874  #Updated with value for O6
    stand_density_sp: # Species-specific stand density [trees ha-1]
      type: fixed
      value: 280000  # Updated for 2010 oak
    Hspec:  #Tree height [m]
      type: fixed
      value: 0.50   # Updated with value for O6
    LAI:  # Species-specific leaf area index [m2leaf m-2 ground]
      type: fixed
      value: 1.58  # Updated for oak from 2011 litter trap measurements (adjusted by optical measurements)

    #########################################################################3
    #NHL PARAMETERS
    ###########################################################################
    scale_nhl:
      type: fixed
      value: 1.0
      #bounds: [0.1, 2.0]

    mean_crown_area_sp: #[m2]
      type: fixed
      value: 0.1  # Updated with value for O6

    Cf:
      type: fixed
      value: 0.85  #Clumping fraction [unitless], assumed to be 0.85 (Forseth & Norman 1993) unless otherwise specified
    x:
      type: range
      bounds: [2.0, 6.0]  # Range from Mirfenderesgi et al 2016, Table 2
      value: 1.0  #Ratio of horizontal to vertical projections of leaves (leaf angle distribution), assumed spherical (x=1)
    Vcmax25:
      type: range
      bounds: [20.0, 100.0]  # Range from Mirfenderesgi et al 2016, Table 2
      value: 69.639 #oak 59.9 pine 31.1
    m:
      type: range
      bounds: [4.0, 9.0] # Range from Mirfenderesgi et al 2016, Table 2
      value: 7.258    # value: #6.7 oak, 7.3 pine

    alpha_p: 
      type: range
      bounds: [0.1, 1.0]
      value: 0.934

    wp_s50:
      type: fixed
      value: -9.1e+5  #-9.1e+5 oak -1.8e+5
      #bounds: [-2.0e+6, -1.0e+5]  # Range from Mirfenderesgi et al 2016, Table 2
    c3:
      type: fixed
      value: 12.3  # value: #12.3 oak 10.3 pine  from Mirfenderesgi
      #bounds: [0.1, 20.0]  # Range from Mirfenderesgi et al 2016, Table 2
  
    #########################################################################
    #Osmoregulation PARAMETERS
    #########################################################################
    filt_eff:  #salt filtration efficiency at the root zone
      type: fixed
      value: 0.95
    iv:  #van't hoff coefficient for NaCl
      type: fixed
      value: 2
    a_sal: 
      type: fixed
      value: 0.5 #a_sal parameter (1/psu) in the equation Vcmax25 salinity reduction eq. Fit from Surez et al 2006 data
      #bounds: [0.01,2.0]
    kvc:
      type: fixed
      value: 23.963 #kvc parameter in eq Vcmax25 salinity reduction eq. Fit from Surez et al 2006 data
      #bounds: [10.0,30.0]
    L_op: 
      type: fixed
      value: 5.9241088890316 #empircal shape parameter for wp_s50 curve fit from Nguyen et al 2017 data
      #bounds: [2.0,10.0]
    k_op: 
      type: fixed
      value: 0.2299963640964328 #empircal shape parameter for wp_s50 curve fit from Nguyen et al 2017 data
      #bounds: [0.01,2.0]
    x0_op:
      type: fixed
      value: -3.704173271499543e-16 #parameter for wp_s50 curve [Mpa] fit from Nguyen et al 2017 data
      #bounds: [-8.0,-1.0]

 
